const SUCCESS_STATUS_NUM = 200;
const NOT_FOUND_STATUS_NUM = 404;
const SUCCESS_STATUS = "success";
const REFUSED_STATUS = "refused";
const GET_ALL_SYMPTOMS_MESSAGE = 'Retrieved all symptoms';
const GET_SYMPTOM_DIAGNOSIS_MESSAGE_SUCCESS = 'Retrieved all diagnosis';
const NOT_FOUND_MESSAGE = 'Not found';
const REPORT_MESSAGE_SUCCESS = 'Send back report';

module.exports = {
    SUCCESS_STATUS_NUM: SUCCESS_STATUS_NUM,
    NOT_FOUND_STATUS_NUM: NOT_FOUND_STATUS_NUM,
    SUCCESS_STATUS: SUCCESS_STATUS,
    REFUSED_STATUS: REFUSED_STATUS,
    GET_ALL_SYMPTOMS_MESSAGE: GET_ALL_SYMPTOMS_MESSAGE,
    GET_SYMPTOM_DIAGNOSIS_MESSAGE_SUCCESS: GET_SYMPTOM_DIAGNOSIS_MESSAGE_SUCCESS,
    NOT_FOUND_MESSAGE: NOT_FOUND_MESSAGE,
    REPORT_MESSAGE_SUCCESS: REPORT_MESSAGE_SUCCESS
}
